name: Publish to Exchange using github

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-asset:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking in repo
      uses: actions/setup-java@v3

    - name: Install Catalog-CLI
      run: |
        sudo apt-get update
        npm install -g api-catalog-cli@latest
    - name: Publish to Exchange
      env:
        PLATFORM_ORGID: ${{ secrets.PLATFORM_ORGID}}
        PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME}}
        PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD}}
      run: |
        api-catalog publish-asset --organization="$PLATFORM_ORGID" --username="$PLATFORM_USERNAME" --password="$PLATFORM_PASSWORD"
